# Generated by Django 4.1.7 on 2023-03-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='application',
            name='employer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employer'),
        ),
    ]
