# Generated by Django 4.1.7 on 2023-03-09 13:13

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_application_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default='profile.jpg', upload_to='profile', validators=[api.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'webp'])]),
        ),
    ]
